### ISSUE TITLE
Imagen de distinto tamaño

### ISSUE THREAD

**Issue by jforni** [AlfonsoWk/ProyectoFinal#15]
Cuando al sitio lo abro en una notebook, la imagen de suplementos queda más chica que la de ropa deportiva.
Ahora, en un monitor de pc de escritorio, se ve bien.
Adjunto imagen:
![image](https://github.com/user-attachments/assets/9e46db9b-5b11-4647-8068-db2ac8142e57)

**Comment by AlfonsoWk** [comment]
![imagen](https://github.com/user-attachments/assets/2b467b36-f88c-4076-b75c-f95be4af5a22)
