### ISSUE TITLE
Label de Plan Contratado en el formulario de registro ubicado distinto al resto

### ISSUE THREAD

**Issue by jforni** [AlfonsoWk/ProyectoFinal#16]
En el formulario de registro la opción de seleccionar el Plan Contratado tiene el label o título de la selección en la parte de arriba, al revés que el resto que los tienen en la parte inferior.
Adjunto imagen
![image](https://github.com/user-attachments/assets/f99b84d2-4d64-4676-be1d-80ef4a297127)

**Comment by AlfonsoWk** [comment]
![imagen](https://github.com/user-attachments/assets/2a832f06-0bd0-4c4b-bd21-886389a9c273)
Se modifica los label del formulario de registro de usuario
