### ISSUE TITLE
Mensaje de error por falta de carga de correo electrónico 

### ISSUE THREAD

**Issue by jforni** [AlfonsoWk/ProyectoFinal#17]
El mensaje de error por falta de carga del correo electrónico, en vez de decir email debería decir correo electrónico. 
Adjunto imagen:
![image](https://github.com/user-attachments/assets/844d981c-3a20-49fc-b549-bf4dbd44c259)

**Comment by AlfonsoWk** [comment]
Arreglado!!
![1](https://github.com/user-attachments/assets/15a671e8-2f21-496c-a2d1-fadcea18f330)
