### ISSUE TITLE
Scroll horizontal

### ISSUE THREAD

**Issue by jforni** [AlfonsoWk/ProyectoFinal#19]
En la sección de registro de usuario, aparece el scroll horizontal.
Adjunto imagen:
![image](https://github.com/user-attachments/assets/b89e201f-7320-490a-97d6-9ba88343d459)

**Comment by AlfonsoWk** [comment]
![imagen](https://github.com/user-attachments/assets/ebe10c06-2a3d-4bfc-8f97-4e8c3e5a5f04)
Se corrige scroll horizontal
