### ISSUE TITLE
Inicio de sesión cuando ya estoy logueado

### ISSUE THREAD

**Issue by jforni** [AlfonsoWk/ProyectoFinal#20]
Quise ver los planes de musculación y me muestra que no estoy logueado:
![image](https://github.com/user-attachments/assets/32e456e0-d71f-4610-8878-566e59b279fd)
Pero cuando presiono en el botón "Iniciar Sesion", me lleva a la pagina para logearme y me muestra que ya stoy logueado
![image](https://github.com/user-attachments/assets/6684f967-9bf0-4b9b-b592-1e3271bdff9d)

**Comment by AlfonsoWk** [comment]
![imagen](https://github.com/user-attachments/assets/31468ffb-486a-4f09-8941-c197efec339c)
Esto me gustaría verlo con vos Julio, porque lo veo distinto.
