### ISSUE TITLE
Botones a distintas alturas

### ISSUE THREAD

**Issue by jforni** [AlfonsoWk/ProyectoFinal#21]
En la sección de planes, los botones están a distintas alturas
Adjunto imagen:
![image](https://github.com/user-attachments/assets/ce6187b5-471c-405c-a117-6996d6fcdc48)

**Comment by AlfonsoWk** [comment]
![imagen](https://github.com/user-attachments/assets/7d3def4d-c4fe-4400-ba85-05800b6d5e7f)
Se corrigen altura de botones
